### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by VamsiSangam** [ITCoders/Human-detection-and-Tracking#16]
The [given link](http://www.pyimagesearch.com/2015/06/22/install-opencv-3-0-and-python-2-7-on-ubuntu/) for linux installation of opencv is meant to install opencv for python 2.7 not python3. As a result upon following those instructions ``` import cv2``` works in python command line but not for python 3.
![screenshot from 2017-03-05 01-20-16](https://cloud.githubusercontent.com/assets/11662001/23581799/061054b4-0142-11e7-9125-77df70658b25.png)

Also upon trying to run code using python 2.7, the output is empty -

![screenshot from 2017-03-05 00-17-08](https://cloud.githubusercontent.com/assets/11662001/23581803/1f71693e-0142-11e7-8277-97949d85d0b1.png)

It would be very helpful if you could add the sample input video for checking the code.

**Comment by arpit1997** [comment]
This link http://www.pyimagesearch.com/2015/06/22/install-opencv-3-0-and-python-2-7-on-ubuntu/ works  perfectly for opencv installation for python3.4. I followed its instructions only for installation. Try to repeat the process again it might work because it took me 5-6 times to install opencv correctly.
You can try this [link](https://drive.google.com/file/d/0B8NEmCEAreTPUlBBUDhFMW1uYkk/view?usp=sharing) also
