### ISSUE TITLE
Runnning it realtime

### ISSUE THREAD

**Issue by Zumbalamambo** [ITCoders/Human-detection-and-Tracking#23]
How do i run this code in realtime camera stream using opencv?

**Comment by arpit1997** [comment]
You need to modify the `main.py` file in order to do that. In 
`if __name__ == '__main__':`

block there are couple of statements to read videos from folders, remove them and then use 

`cap = cv2.VideoCapture(0)`

 in order to open the default camera. If you want to connect some other camera then you need to connect some other interface in order to supply video frames continuously to the code.

**Comment by Zumbalamambo** [comment]
It always detects either 1 or 2. What if there are more than two person

**Comment by arpit1997** [comment]
If you want to detect other people then you have to train your own model. There is a script in the repo which trains a face recognition model based on the images you specify. Sample images can be seen in the repo itself

**Comment by Zumbalamambo** [comment]
@arpit1997 How do I train realtime?
