### ISSUE TITLE
openCV Problem

### ISSUE THREAD

**Issue by rachana88** [ITCoders/Human-detection-and-Tracking#27]
I am getting this error . please anyone help me on this 
File "main.py", line 17, in <module>
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2.cv2' has no attribute 'face'

**Comment by arpit1997** [comment]
@rachana88 Please mention your python version, operating system and opencv version that you are using. cc: @prsntmaurya

**Comment by prsntmaurya** [comment]
As further information is not provided, I assume this issue has been resolved. If there will be no further discussion in next few days this issue will be closed.

**Comment by riteshhota2008** [comment]
I am getting the same error. 

File "main.py", line 17, in 
recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2.cv2' has no attribute 'face'

Python version - 3.6.5
OS - Mac Os
Opencv Version -  3.4.0

**Comment by prsntmaurya** [comment]
Hi Ritesh,
Please ensure that your OpenCV is compiled with contrib_modules.
If it has already complied with contrib_modules then the error is because you are using OpenCV version 3.4 and this repository was written using OpenCV version 3.1.

If you don't want to switch your OpenCV version please refer to Issue #25 where this problem is already fixed.
